/*Q9. COUNT ORDERS BY STATUS

Using conditional aggregation, calculate:

- Total Completed Orders
- Total Cancelled Orders
- Total Pending Orders
- Total Other Orders

Return everything in one row.
*/
select DISTINCT(Order_Status) from orders;

SELECT
SUM(CASE WHEN lower(order_status)= 'cancelled' THEN 1 ELSE 0 END) as cancelled,
SUM(CASE WHEN lower(order_status)= 'complete' THEN 1 ELSE 0 END) as completed,
SUM(CASE WHEN lower(order_status)= 'refunded' THEN 1 ELSE 0 END) as refund
FROM orders;


/*
Q10. REVENUE BY PRICE CATEGORY

Classify products into:

- Low Price
- Medium Price
- High Price

Then calculate total revenue generated by each
price category.

Revenue:
Unit_Price * Quantity

Return:
- Price_Category
- Total_Revenue
*/

WITH Product_Category AS (
    SELECT
        Product_Id,
        CASE
            WHEN Unit_Price < 1000 THEN 'Low'
            WHEN Unit_Price <= 10000 THEN 'Medium'
            ELSE 'High'
        END AS Price_Category
    FROM products
)
SELECT
    pc.Price_Category,
    SUM(oi.Unit_Price * oi.Quantity) AS Total_Revenue
FROM Product_Category pc
JOIN order_items oi
    ON pc.Product_Id = oi.Product_Id
GROUP BY pc.Price_Category
ORDER BY Total_Revenue DESC;

/*
Q11. CUSTOMER ACTIVITY CATEGORIES

For every customer, calculate their total number
of orders.

Classify customers:

- 0 orders       → 'No Orders'
- 1 order        → 'Single Order'
- 2–5 orders     → 'Regular'
- More than 5    → 'Frequent'

Return:
- Customer_ID
- Full_Name
- Order_Count
- Customer_Category
*/

SELECT
    c.Customer_ID,c.Full_Name,COUNT(o.Order_Id) AS Order_Count,
    CASE
        WHEN COUNT(o.Order_Id) = 0 THEN 'No Orders'
        WHEN COUNT(o.Order_Id) = 1 THEN 'Single Order'
        WHEN COUNT(o.Order_Id) BETWEEN 2 AND 5 THEN 'Regular'
        ELSE 'Frequent'
    END AS Customer_Category
FROM customers c
LEFT JOIN orders o
ON c.Customer_ID = o.Customer_ID
GROUP BY c.Customer_ID,c.Full_Name
ORDER BY Order_Count DESC;

/*
Q12. STORE REVENUE CLASSIFICATION

Calculate total revenue for every store.

Classify stores into:

- 'Low Revenue'
- 'Medium Revenue'
- 'High Revenue'

Choose reasonable revenue thresholds based on
the actual CO dataset.

Return:
- Store_Id
- Store_Name
- Total_Revenue
- Revenue_Category
*/

WITH Store_Revenue AS (
    SELECT
        s.Store_Id,
        s.Store_Name,
        COALESCE(SUM(oi.Unit_Price * oi.Quantity), 0) AS Total_Revenue
    FROM stores s
    LEFT JOIN orders o
        ON s.Store_Id = o.Store_Id
    LEFT JOIN order_items oi
        ON o.Order_Id = oi.Order_Id
    GROUP BY
        s.Store_Id,
        s.Store_Name
),
Store_Average AS (
    SELECT
        *,
        AVG(Total_Revenue) OVER () AS Average_Revenue
    FROM Store_Revenue
)
SELECT
    Store_Id,
    Store_Name,
    Total_Revenue,
    Average_Revenue,
    CASE
        WHEN Total_Revenue >= Average_Revenue * 1.5
            THEN 'High Revenue'

        WHEN Total_Revenue >= Average_Revenue
            THEN 'Medium Revenue'

        ELSE 'Low Revenue'
    END AS Revenue_Category
FROM Store_Average
ORDER BY Total_Revenue DESC;

/*
Q13. PRODUCT DEMAND CLASSIFICATION

Calculate total quantity sold for every product.

Classify products into:

- 'Low Demand'
- 'Medium Demand'
- 'High Demand'

Choose reasonable thresholds based on the dataset.

Return:
- Product_Id
- Product_Name
- Total_Quantity
- Demand_Category
*/

WITH Product_Demand AS (
    SELECT
        p.Product_Id,
        p.Product_Name,
        COALESCE(SUM(oi.Quantity), 0) AS Total_Quantity
    FROM products p
    LEFT JOIN order_items oi
        ON p.Product_Id = oi.Product_Id
    GROUP BY
        p.Product_Id,
        p.Product_Name
),
Product_Average AS (
    SELECT
        *,
        AVG(Total_Quantity) OVER () AS Average_Quantity
    FROM Product_Demand
)
SELECT
    Product_Id,
    Product_Name,
    Total_Quantity,
    Average_Quantity,
    CASE
        WHEN Total_Quantity >= Average_Quantity * 1.5
            THEN 'High Demand'

        WHEN Total_Quantity >= Average_Quantity
            THEN 'Medium Demand'

        ELSE 'Low Demand'
    END AS Demand_Category
FROM Product_Average
ORDER BY Total_Quantity DESC;


/*
Q14. CUSTOMER VALUE CLASSIFICATION

For every customer calculate:

- Total Orders
- Total Revenue

Classify customers into:

- 'High Value'
- 'Medium Value'
- 'Low Value'

Use CASE WHEN based on Total_Revenue.

Return:
- Customer_ID
- Full_Name
- Total_Orders
- Total_Revenue
- Customer_Category
*/

SELECT
    c.Customer_ID,
    c.Full_Name,
    COUNT(DISTINCT o.Order_Id) AS Total_Orders,
    COALESCE(
        SUM(oi.Unit_Price * oi.Quantity),
        0
    ) AS Total_Revenue,

    CASE
        WHEN COALESCE(SUM(oi.Unit_Price * oi.Quantity), 0) >= 100000
            THEN 'High Value'

        WHEN COALESCE(SUM(oi.Unit_Price * oi.Quantity), 0) >= 50000
            THEN 'Medium Value'

        ELSE 'Low Value'
    END AS Customer_Category

FROM customers c

LEFT JOIN orders o
    ON c.Customer_ID = o.Customer_ID

LEFT JOIN order_items oi
    ON o.Order_Id = oi.Order_Id

GROUP BY
    c.Customer_ID,
    c.Full_Name

ORDER BY Total_Revenue DESC;


/*
Q15. SHIPMENT PERFORMANCE SUMMARY

Using CASE WHEN and conditional aggregation,
calculate:

- Delivered shipments
- In-transit shipments
- Pending shipments
- Other shipments

Return all four counts in one row.
*/

SELECT
    SUM(
        CASE
            WHEN LOWER(Shipment_Status) = 'delivered'
            THEN 1
            ELSE 0
        END
    ) AS Delivered_Count,

    SUM(
        CASE
            WHEN LOWER(Shipment_Status) = 'in transit'
            THEN 1
            ELSE 0
        END
    ) AS In_Transit_Count,

    SUM(
        CASE
            WHEN LOWER(Shipment_Status) = 'pending'
            THEN 1
            ELSE 0
        END
    ) AS Pending_Count,

    SUM(
        CASE
            WHEN LOWER(Shipment_Status) NOT IN
                 ('delivered', 'in transit', 'pending')
            THEN 1
            ELSE 0
        END
    ) AS Other_Count

FROM shipments;



/*
Q16. STORE INVENTORY HEALTH

For every store, count the number of products
belonging to each inventory category:

- Out of Stock
- Low Stock
- Medium Stock
- High Stock

Return:
- Store_Id
- Out_of_Stock_Count
- Low_Stock_Count
- Medium_Stock_Count
- High_Stock_Count
*/


SELECT
    Store_Id,

    SUM(
        CASE
            WHEN Product_Inventory = 0
            THEN 1
            ELSE 0
        END
    ) AS Out_of_Stock_Count,

    SUM(
        CASE
            WHEN Product_Inventory BETWEEN 1 AND 10
            THEN 1
            ELSE 0
        END
    ) AS Low_Stock_Count,

    SUM(
        CASE
            WHEN Product_Inventory BETWEEN 11 AND 50
            THEN 1
            ELSE 0
        END
    ) AS Medium_Stock_Count,

    SUM(
        CASE
            WHEN Product_Inventory > 50
            THEN 1
            ELSE 0
        END
    ) AS High_Stock_Count

FROM inventory
GROUP BY Store_Id
ORDER BY Store_Id;