/*   Q6. Show each order alongside the total number of orders placed by the same customer. 
Use COUNT() OVER(PARTITION BY Customer_ID). 
Show order ID, customer ID and customer order count.  */

SELECT order_id, customer_id, COUNT(order_id) OVER(PARTITION BY customer_id) AS customer_order_count
FROM orders;


/*  Q7. Show each order item alongside the total revenue generated by the same product across all orders.
 Use SUM() OVER(PARTITION BY Product_ID). 
 Show order ID, product ID, unit price, quantity and product total revenue.   */

SELECT order_id, product_id, unit_price, quantity, SUM(unit_price * Quantity) OVER(PARTITION BY product_id) AS product_total_revenue
FROM order_items;

/*   Q8. Show each order alongside the total revenue of all orders placed through the same store. 
Use SUM() OVER(PARTITION BY Store_Id). 
Show order ID, store ID and store total revenue.  */

SELECT o.order_id, o.store_id, SUM(oi.unit_price * oi.Quantity) OVER(PARTITION BY o.store_id)
FROM orders o
JOIN order_items oi
ON o.order_id = oi.Order_Id;

/*  Q9. Show each inventory record alongside the total inventory available at the same store. 
Use SUM() OVER(PARTITION BY Store_Id). 
Show store ID, product ID, product inventory and store total inventory.   */

SELECT i.store_id, i.product_id, i.product_inventory, SUM(Product_Inventory) OVER (PARTITION BY Store_Id) AS store_total_inventory
FROM Inventory i
JOIN stores s 
ON i.store_id = s.Store_Id;


/*  Q10. Show each order item alongside the average unit price of all items within the same order. 
Use AVG() OVER(PARTITION BY Order_Id). 
Show order ID, product ID, unit price and order average price.   */

SELECT order_id, product_id, unit_price, AVG(unit_price) OVER(partition by order_Id) AS Order_Average_Price
FROM order_items;


/*  Q11. Show each order alongside the maximum and minimum unit price charged across all items in the same order. 
Use MAX() and MIN() OVER(PARTITION BY Order_Id) by joining Orders and Order_Items. 
Show order ID, product ID, unit price, order max price and order min price.   */

SELECT o.order_Id, oi.product_Id, oi.unit_price, MAX(oi.unit_price) OVER w as Order_Max_Price, MIN(oi.unit_price) OVER w AS Order_Min_Price
FROM orders o
JOIN order_items oi
ON o.Order_Id = oi.Order_Id
WINDOW w AS (partition by oi.Order_Id);

