/*
Q1. Calculate total revenue generated by each customer and show
    each customer's percentage contribution to overall revenue.
*/

WITH Customer_Revenue AS (
    SELECT
        o.Customer_ID,
        SUM(
            oi.Quantity * oi.Unit_Price
        ) AS Revenue
    FROM CO.Orders o
    INNER JOIN CO.Order_Items oi
        ON o.Order_Id = oi.Order_Id
    GROUP BY o.Customer_ID
)

SELECT
    Customer_ID,
    Revenue,

    ROUND(
        Revenue * 100.0
        / SUM(Revenue) OVER (),
        2
    ) AS Revenue_Pct

FROM Customer_Revenue

ORDER BY Revenue DESC;


/*
Q2. Find the top 10 customers by revenue and show their
    percentage contribution to total company revenue.
*/

WITH Customer_Revenue AS (
    SELECT
        o.Customer_ID,
        SUM(
            oi.Quantity * oi.Unit_Price
        ) AS Revenue
    FROM CO.Orders o
    INNER JOIN CO.Order_Items oi
        ON o.Order_Id = oi.Order_Id
    GROUP BY o.Customer_ID
),

Ranked_Customers AS (
    SELECT
        Customer_ID,
        Revenue,

        RANK() OVER (
            ORDER BY Revenue DESC
        ) AS Revenue_Rank

    FROM Customer_Revenue
)

SELECT
    Customer_ID,
    Revenue,
    Revenue_Rank,

    ROUND(
        Revenue * 100.0
        / SUM(Revenue) OVER (),
        2
    ) AS Revenue_Pct

FROM Ranked_Customers

WHERE Revenue_Rank <= 10

ORDER BY Revenue_Rank;


/*
Q3. Calculate total revenue per store and show each store's
    percentage contribution to total revenue.
*/

WITH Store_Revenue AS (
    SELECT
        o.Store_Id,

        SUM(
            oi.Quantity * oi.Unit_Price
        ) AS Revenue

    FROM CO.Orders o

    INNER JOIN CO.Order_Items oi
        ON o.Order_Id = oi.Order_Id

    GROUP BY o.Store_Id
)

SELECT
    Store_Id,
    Revenue,

    ROUND(
        Revenue * 100.0
        / SUM(Revenue) OVER (),
        2
    ) AS Revenue_Pct

FROM Store_Revenue

ORDER BY Revenue DESC;


/*
Q4. Calculate the cumulative percentage of total revenue
    contributed by customers ordered from highest to lowest revenue.
*/

WITH Customer_Revenue AS (
    SELECT
        o.Customer_ID,

        SUM(
            oi.Quantity * oi.Unit_Price
        ) AS Revenue

    FROM CO.Orders o

    INNER JOIN CO.Order_Items oi
        ON o.Order_Id = oi.Order_Id

    GROUP BY o.Customer_ID
),

Customer_Cumulative AS (
    SELECT
        Customer_ID,
        Revenue,

        SUM(Revenue) OVER (
            ORDER BY Revenue DESC
            ROWS BETWEEN UNBOUNDED PRECEDING
                     AND CURRENT ROW
        ) AS Cumulative_Revenue,

        SUM(Revenue) OVER () AS Total_Revenue

    FROM Customer_Revenue
)

SELECT
    Customer_ID,
    Revenue,
    Cumulative_Revenue,

    ROUND(
        Cumulative_Revenue * 100.0
        / Total_Revenue,
        2
    ) AS Cumulative_Revenue_Pct

FROM Customer_Cumulative

ORDER BY Revenue DESC;


/*
Q5. Find the customers responsible for the first 80% of
    total revenue.
*/

WITH Customer_Revenue AS (
    SELECT
        o.Customer_ID,

        SUM(
            oi.Quantity * oi.Unit_Price
        ) AS Revenue

    FROM CO.Orders o

    INNER JOIN CO.Order_Items oi
        ON o.Order_Id = oi.Order_Id

    GROUP BY o.Customer_ID
),

Revenue_Cumulative AS (
    SELECT
        Customer_ID,
        Revenue,

        SUM(Revenue) OVER (
            ORDER BY Revenue DESC
            ROWS BETWEEN UNBOUNDED PRECEDING
                     AND CURRENT ROW
        ) AS Running_Revenue,

        SUM(Revenue) OVER () AS Total_Revenue

    FROM Customer_Revenue
)

SELECT
    Customer_ID,
    Revenue,

    ROUND(
        Running_Revenue * 100.0
        / Total_Revenue,
        2
    ) AS Cumulative_Revenue_Pct

FROM Revenue_Cumulative

WHERE Running_Revenue <=
      Total_Revenue * 0.80

ORDER BY Revenue DESC;


/*
Q6. Calculate each product's percentage contribution to
    total product revenue.
*/

WITH Product_Revenue AS (
    SELECT
        Product_Id,

        SUM(
            Quantity * Unit_Price
        ) AS Revenue

    FROM CO.Order_Items

    GROUP BY Product_Id
)

SELECT
    Product_Id,
    Revenue,

    ROUND(
        Revenue * 100.0
        / SUM(Revenue) OVER (),
        2
    ) AS Revenue_Pct

FROM Product_Revenue

ORDER BY Revenue DESC;

